import {
  BAR_GAP,
  LANE_HEIGHT,
  MAX_LANES,
  NUMBER_HEIGHT
} from '../month/constants'

export const MONTH_HELPERS: readonly string[] = [
  `const MONTH_LANE_HEIGHT = ${LANE_HEIGHT}`,
  `const MAX_LANES = ${MAX_LANES}`,
  `const NUMBER_HEIGHT = ${NUMBER_HEIGHT}`,
  `const BAR_GAP = ${BAR_GAP}`,
  ''
]

export const MONTH_BODY: readonly string[] = [
  '          <Calendar.MonthGrid>',
  '            <div',
  '              className="grid border-b border-slate-200 dark:border-white/15"',
  '              style={{ gridTemplateColumns: "repeat(7, minmax(0, 1fr))" }}',
  '            >',
  '              <Calendar.MonthWeekdays',
  '                as="span"',
  '                className="border-l border-slate-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-slate-500 uppercase first:border-l-0 dark:border-white/5 dark:text-slate-400"',
  '              />',
  '            </div>',
  '',
  '            <Calendar.MonthRows',
  '              className="border-b border-slate-200 last:border-b-0 dark:border-white/15"',
  '              laneHeight={MONTH_LANE_HEIGHT}',
  '              maxLanes={MAX_LANES}',
  '              style={{ minHeight: 116 }}',
  '            >',
  '              <Calendar.MonthDays className="flex flex-col border-l border-slate-100 px-1 pb-1 first:border-l-0 dark:border-white/5 data-[in-current-period=false]:bg-slate-50 data-[in-current-period=false]:text-slate-400 dark:data-[in-current-period=false]:bg-slate-950">',
  '                {({ day, dayLabel, lanes, hiddenBars }) => (',
  '                  <>',
  '                    <span',
  '                      className="flex items-center justify-center text-xs font-medium"',
  '                      style={{ height: NUMBER_HEIGHT }}',
  '                    >',
  '                      <span className={day.date === today ? "rounded-full bg-orange-100 px-2 dark:bg-orange-900" : ""}>',
  '                        {dayLabel}',
  '                      </span>',
  '                    </span>',
  '',
  '                    <span',
  '                      className="block"',
  '                      style={{ height: lanes * MONTH_LANE_HEIGHT }}',
  '                    />',
  '',
  '                    {hiddenBars.length > 0 && (',
  '                      <span className="px-1 text-[10px] font-medium text-slate-500">',
  '                        +{hiddenBars.length} more',
  '                      </span>',
  '                    )}',
  '',
  '                    <span className="flex flex-col gap-0.5">',
  '                      <Calendar.MonthTimedEvents',
  '                        as="span"',
  '                        className="truncate rounded px-1 text-[11px] leading-5 bg-violet-700 text-white dark:bg-violet-400 dark:text-slate-950"',
  '                      >',
  '                        {({ event }) => event.data?.title ?? event.id}',
  '                      </Calendar.MonthTimedEvents>',
  '                    </span>',
  '                  </>',
  '                )}',
  '              </Calendar.MonthDays>',
  '',
  '              <Calendar.MonthAllDayEvents',
  '                gap={BAR_GAP}',
  '                lanesTopOffset={NUMBER_HEIGHT}',
  '              >',
  '                {({ event }) => (',
  '                  <span',
  '                    className={`flex h-full items-center truncate rounded px-1.5 text-[11px] font-medium bg-blue-700 text-white dark:bg-blue-300 dark:text-slate-950`}',
  '                  >',
  '                    {event.data?.title ?? event.id}',
  '                  </span>',
  '                )}',
  '              </Calendar.MonthAllDayEvents>',
  '            </Calendar.MonthRows>',
  '          </Calendar.MonthGrid>'
]
