export const AGENDA_RENDER: readonly string[] = [
  'const renderAgenda = (calendar: CalendarLayout<EventData>): string => {',
  '  const days = calendar.days',
  '  let taken = 0',
  '  const dayBars: any[][] = days.map(() => [])',
  '  for (const row of calendar.rows) {',
  '    for (const bar of row.bars) {',
  '      for (let offset = bar.startDay; offset < bar.endDay; offset += 1) {',
  '        dayBars[taken + offset]?.push(bar)',
  '      }',
  '    }',
  '    taken += row.dayCount',
  '  }',
  '',
  '  const itemsHtml = days.map((day, index) => {',
  "    const weekday = formatIso(day.date, { locale: LOCALE, options: { weekday: 'short' } })",
  "    const dayNum = formatIso(day.date, { locale: LOCALE, options: { day: 'numeric' } })",
  '    const bars = dayBars[index] ?? []',
  '    const boxes = day.boxes',
  '    const isEmpty = bars.length === 0 && boxes.length === 0',
  '',
  '    const allDayEvents = bars.map((bar) => `',
  '      <span class="flex items-center gap-2 text-[13px]">',
  '        <span class="size-2 shrink-0 rounded-full bg-blue-600"></span>',
  '        <span class="w-24 shrink-0 text-[11px] text-slate-400">all-day</span>',
  '        <span class="truncate">${bar.event.data?.title ?? bar.event.id}</span>',
  "      </span>`).join('')",
  '',
  '    const timedEvents = boxes.map((box) => {',
  "      const from = formatIso(box.start, { locale: LOCALE, options: { hour: '2-digit', minute: '2-digit' } })",
  "      const to = formatIso(box.end, { locale: LOCALE, options: { hour: '2-digit', minute: '2-digit' } })",
  '      return `',
  '        <span class="flex items-center gap-2 text-[13px]">',
  '          <span class="size-2 shrink-0 rounded-full bg-violet-600"></span>',
  '          <span class="w-24 shrink-0 font-mono text-[11px] tabular-nums text-slate-500">${from} – ${to}</span>',
  '          <span class="truncate">${box.event.data?.title ?? box.event.id}</span>',
  '        </span>`',
  "    }).join('')",
  '',
  '    return `',
  '      <li class="grid grid-cols-[88px_minmax(0,1fr)] gap-4 px-4 py-3">',
  '        <div class="flex items-baseline gap-2">',
  '          <span class="flex size-7 items-center justify-center text-sm font-semibold">${dayNum}</span>',
  '          <span class="text-[11px] tracking-wide text-slate-500 uppercase">${weekday}</span>',
  '        </div>',
  '        <div class="flex flex-col gap-1">',
  "          ${isEmpty ? '<span class=\"text-[13px] text-slate-400\">No events</span>' : ''}",
  '          ${allDayEvents}',
  '          ${timedEvents}',
  '        </div>',
  '      </li>`',
  "  }).join('')",
  '',
  '  return `<ul class="divide-y divide-slate-100 dark:divide-white/5">${itemsHtml}</ul>`',
  '}',
  ''
]
