export const MONTH_HELPERS: readonly string[] = [
  'const CELL_MIN_HEIGHT = 120',
  'const LANE_HEIGHT = 20',
  'const NUMBER_HEIGHT = 28',
  'const MAX_LANES = 3',
  'const BAR_GAP = 4',
  ''
]

export const MONTH_RENDER: readonly string[] = [
  'const renderMonth = (calendar: CalendarLayout<EventData>): string => {',
  '  let taken = 0',
  '  const rows = calendar.rows.map((row) => {',
  '    const days = calendar.days.slice(taken, taken + row.dayCount)',
  '    taken += row.dayCount',
  '    return { row, days }',
  '  })',
  '',
  '  const weekdays = rows[0]?.days.map((day) => `',
  '    <span class="border-l border-slate-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-slate-500 uppercase first:border-l-0 dark:border-white/5 dark:text-slate-400">',
  "      ${formatIso(day.date, { locale: LOCALE, options: { weekday: 'short' } })}",
  '    </span>',
  "  `).join('') ?? ''",
  '',
  '  const rowsHtml = rows.map(({ row, days }) => {',
  '    const lanes = Math.min(row.lanes, MAX_LANES)',
  '    const daysHtml = days.map((day) => {',
  "      const dayNum = formatIso(day.date, { locale: LOCALE, options: { day: 'numeric' } })",
  '      const timed = day.boxes.map((b) => `',
  '        <span class="flex items-center gap-1 truncate rounded bg-violet-700 px-1 text-[11px] leading-5 text-white dark:bg-violet-400 dark:text-slate-950">',
  '          <span class="truncate">${b.event.data?.title ?? b.event.id}</span>',
  "        </span>`).join('')",
  '      return `',
  '        <div class="flex flex-col border-l border-slate-100 px-1 pb-1 first:border-l-0 dark:border-white/5">',
  '          <span class="flex items-center justify-center text-xs font-medium" style="height: ${NUMBER_HEIGHT}px;">${dayNum}</span>',
  '          <span class="block" style="height: ${lanes * LANE_HEIGHT}px;"></span>',
  '          <span class="flex flex-col gap-0.5">${timed}</span>',
  '        </div>`',
  "    }).join('')",
  '',
  '    const bars = row.bars.filter((b) => b.lane < MAX_LANES).map((bar) => `',
  '      <div style="position: absolute; left: calc(${bar.left * 100}% + ${BAR_GAP / 2}px); width: calc(${bar.width * 100}% - ${BAR_GAP}px); top: ${NUMBER_HEIGHT + bar.lane * LANE_HEIGHT}px; height: ${LANE_HEIGHT}px; z-index: 1;">',
  '        <span class="flex h-full items-center truncate rounded bg-blue-700 px-1.5 text-[11px] font-medium text-white dark:bg-blue-300 dark:text-slate-950">',
  '          ${bar.event.data?.title ?? bar.event.id}',
  '        </span>',
  "      </div>`).join('')",
  '',
  '    return `',
  '      <div class="border-b border-slate-200 last:border-b-0 dark:border-white/15" style="position: relative; flex: 1; display: grid; grid-template-columns: repeat(${days.length}, minmax(0, 1fr)); min-height: ${CELL_MIN_HEIGHT}px;">',
  '        ${daysHtml}',
  '        ${bars}',
  '      </div>`',
  "  }).join('')",
  '',
  '  return `',
  '    <div>',
  '      <div class="grid border-b border-slate-200 dark:border-white/15" style="grid-template-columns: repeat(7, minmax(0, 1fr));">',
  '        ${weekdays}',
  '      </div>',
  '      ${rowsHtml}',
  '    </div>`',
  '}',
  ''
]
