import {
  ALL_DAY_LANE_HEIGHT,
  BOX_GAP,
  MIN_BOX_HEIGHT,
  SCROLL_TO_HOUR
} from '@midstem/playground-core'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const LANE_HEIGHT = ${ALL_DAY_LANE_HEIGHT}`,
  `const MIN_BOX_HEIGHT = ${MIN_BOX_HEIGHT}`,
  `const BOX_GAP = ${BOX_GAP}`,
  `const SCROLL_TO_HOUR = ${SCROLL_TO_HOUR}`,
  ''
]

export const SLOTTED_RENDER: readonly string[] = [
  'const renderSlotted = (calendar: CalendarLayout<EventData>): string => {',
  '  const days = calendar.days',
  '  const dayHeight = HOUR_HEIGHT * 24',
  '  const row = calendar.rows[0]',
  '  const lanes = row ? row.lanes : 0',
  '  const colsTemplate = `66px repeat(${days.length}, minmax(0, 1fr))`',
  '',
  '  const dayHeadings = days',
  '    .map((day) => {',
  "      const weekday = formatIso(day.date, { locale: LOCALE, options: { weekday: 'short' } })",
  "      const dayNum = formatIso(day.date, { locale: LOCALE, options: { day: 'numeric' } })",
  '      return `',
  '        <div class="border-l border-slate-100 py-2 dark:border-white/5">',
  '          <div class="flex flex-col items-center gap-0.5">',
  '            <span class="text-[10px] font-medium tracking-wide text-slate-500 uppercase dark:text-slate-400">${weekday}</span>',
  '            <span class="flex size-7 items-center justify-center text-sm font-semibold">${dayNum}</span>',
  '          </div>',
  '        </div>`',
  "    }).join('')",
  '',
  '  const allDayRow = lanes > 0 && row ? `',
  '    <div class="border-b border-slate-200 pt-0.5 pb-1.5 dark:border-white/15" style="display: grid; grid-template-columns: ${colsTemplate};">',
  '      <span class="block pt-1 pr-2 text-right text-[10px] text-slate-400">all-day</span>',
  '      <div style="grid-column: 2 / -1; position: relative; height: ${lanes * LANE_HEIGHT}px;">',
  '        ${row.bars.map((bar) => `',
  '          <div style="position: absolute; left: calc(${bar.left * 100}% + 2px); width: calc(${bar.width * 100}% - 4px); top: ${bar.lane * LANE_HEIGHT}px; height: ${LANE_HEIGHT}px;" class="px-px py-px">',
  '            <span class="flex h-full items-center truncate rounded-md bg-blue-700 px-2 text-[11px] font-medium text-white dark:bg-blue-300 dark:text-slate-950">',
  '              ${bar.event.data?.title ?? bar.event.id}',
  '            </span>',
  "          </div>`).join('')}",
  '      </div>',
  "    </div>` : ''",
  '',
  '  const firstDay = days[0]',
  '  const timeLabels = firstDay',
  '    ? firstDay.slots',
  '        .filter((s) => s.minuteOfDay > 0)',
  '        .map((s) => `',
  '          <div class="right-2 text-[10px] tabular-nums text-slate-400" style="position: absolute; top: ${(s.minuteOfDay / 1440) * 100}%; transform: translateY(-50%);">',
  '            ${clock(s.start)}',
  '          </div>`)',
  "        .join('')",
  "    : ''",
  '',
  '  const dayColumns = days',
  '    .map((day) => {',
  '      const slots = day.slots.map((s) =>',
  '        `<span class="border-t border-slate-100 dark:border-white/5" style="position: absolute; left: 0; right: 0; top: ${(s.minuteOfDay / 1440) * 100}%;"></span>`',
  "      ).join('')",
  '      const boxes = day.boxes.map((box) => `',
  '        <div style="position: absolute; overflow: hidden; top: ${box.top * 100}%; height: ${box.height * 100}%; left: ${box.left * 100}%; width: calc(${box.width * 100}% - ${BOX_GAP}px); min-height: ${MIN_BOX_HEIGHT}px;">',
  '          <div class="h-full overflow-hidden rounded-md border border-white bg-violet-700 px-1.5 py-px text-[11px] leading-[1.35] text-white shadow-sm dark:border-slate-900 dark:bg-violet-400 dark:text-slate-950" title="${box.event.data?.title ?? box.event.id}">',
  '            <span class="block truncate font-semibold">${box.event.data?.title ?? box.event.id}</span>',
  '            <span class="block truncate opacity-80">${clock(box.start)} – ${clock(box.end)}</span>',
  '          </div>',
  '        </div>`',
  "      ).join('')",
  '      return `',
  '        <div class="border-l border-slate-100 dark:border-white/5" style="position: relative; height: ${dayHeight}px;">',
  '          ${slots}',
  '          ${boxes}',
  '        </div>`',
  "    }).join('')",
  '',
  '  return `',
  '    <div class="sticky top-0 z-30 bg-white dark:bg-slate-950">',
  '      <div class="border-b border-slate-200 dark:border-white/15" style="display: grid; grid-template-columns: ${colsTemplate};">',
  '        <div></div>',
  '        ${dayHeadings}',
  '      </div>',
  '      ${allDayRow}',
  '    </div>',
  '    <div style="overflow-y: auto;" data-scroller>',
  '      <div style="display: grid; grid-template-columns: ${colsTemplate};">',
  '        <div style="position: relative; height: ${dayHeight}px;">${timeLabels}</div>',
  '        ${dayColumns}',
  '      </div>',
  '    </div>`',
  '}',
  ''
]
