export const AGENDA_BODY: readonly string[] = [
  '        <Calendar.AgendaList as="ul" class="divide-y divide-zinc-100 dark:divide-zinc-800">',
  '          <Calendar.AgendaDays',
  '            as="li"',
  '            show-empty-days',
  '            class="grid grid-cols-[88px_minmax(0,1fr)] gap-4 px-4 py-3 data-[in-current-period=false]:bg-zinc-50 dark:data-[in-current-period=false]:bg-zinc-950"',
  '            v-slot="{ weekdayLabel, dayLabel, bars, boxes }"',
  '          >',
  '            <div class="flex items-baseline gap-2">',
  '              <span class="flex size-7 items-center justify-center text-sm font-semibold">',
  '                {{ dayLabel }}',
  '              </span>',
  '              <span class="text-[11px] tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  '                {{ weekdayLabel }}',
  '              </span>',
  '            </div>',
  '',
  '            <div class="flex flex-col gap-1">',
  '              <span',
  '                v-if="bars.length === 0 && boxes.length === 0"',
  '                class="text-[13px] text-zinc-400 dark:text-zinc-500"',
  '              >',
  '                Nothing on this day',
  '              </span>',
  '',
  '              <Calendar.AgendaAllDayEvents as="span" class="flex items-center gap-2 text-[13px]" v-slot="{ event }">',
  '                <span class="w-24 shrink-0 text-[11px] text-zinc-400 dark:text-zinc-500">',
  '                  all-day',
  '                </span>',
  '                <span class="truncate">{{ event.data?.title }}</span>',
  '              </Calendar.AgendaAllDayEvents>',
  '',
  '              <Calendar.AgendaTimedEvents as="span" class="flex items-center gap-2 text-[13px]" v-slot="{ event, timeRangeLabel }">',
  '                <span class="w-24 shrink-0 font-mono text-[11px] tabular-nums text-zinc-500 dark:text-zinc-400">',
  '                  {{ timeRangeLabel }}',
  '                </span>',
  '                <span class="truncate">{{ event.data?.title }}</span>',
  '              </Calendar.AgendaTimedEvents>',
  '            </div>',
  '          </Calendar.AgendaDays>',
  '        </Calendar.AgendaList>'
]
