import {
  MONTH_BAR_GAP,
  MONTH_LANE_HEIGHT,
  MONTH_MAX_LANES,
  NUMBER_HEIGHT
} from '@midstem/playground-core'

export const MONTH_HELPERS: readonly string[] = [
  `const MONTH_LANE_HEIGHT = ${MONTH_LANE_HEIGHT}`,
  `const MONTH_MAX_LANES = ${MONTH_MAX_LANES}`,
  `const NUMBER_HEIGHT = ${NUMBER_HEIGHT}`,
  `const BAR_GAP = ${MONTH_BAR_GAP}`,
  ''
]

export const MONTH_BODY: readonly string[] = [
  '        <Calendar.MonthGrid>',
  '          <div',
  '            class="grid border-b border-slate-200 dark:border-white/15"',
  '            style="grid-template-columns: repeat(7, minmax(0, 1fr))"',
  '          >',
  '            <Calendar.MonthWeekdays',
  '              as="span"',
  '              class="border-l border-slate-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-slate-500 uppercase first:border-l-0 dark:border-white/5 dark:text-slate-400"',
  '            />',
  '          </div>',
  '',
  '          <Calendar.MonthRows',
  '            class="border-b border-slate-200 last:border-b-0 dark:border-white/15"',
  '            :lane-height="MONTH_LANE_HEIGHT"',
  '            :max-lanes="MONTH_MAX_LANES"',
  '            style="min-height: 116px"',
  '          >',
  '            <Calendar.MonthDays',
  '              class="flex flex-col border-l border-slate-100 px-1 pb-1 first:border-l-0 dark:border-white/5 data-[in-current-period=false]:bg-slate-50 data-[in-current-period=false]:text-slate-400 dark:data-[in-current-period=false]:bg-slate-950"',
  '              v-slot="{ day, dayLabel, lanes, hiddenBars }"',
  '            >',
  '              <span',
  '                class="flex items-center justify-center text-xs font-medium"',
  '                :style="{ height: `${NUMBER_HEIGHT}px` }"',
  '              >',
  "                <span :class=\"day.date === today?.date ? 'rounded-full bg-orange-100 px-2 dark:bg-orange-900' : ''\">{{ dayLabel }}</span>",
  '              </span>',
  '',
  '              <span',
  '                class="block"',
  '                :style="{ height: `${lanes * MONTH_LANE_HEIGHT}px` }"',
  '              />',
  '',
  '              <span',
  '                v-if="hiddenBars.length > 0"',
  '                class="px-1 text-[10px] font-medium text-slate-500"',
  '              >+{{ hiddenBars.length }} more</span>',
  '',
  '              <span class="flex flex-col gap-0.5">',
  '                <Calendar.MonthTimedEvents',
  '                  as="span"',
  '                  class="truncate rounded px-1 text-[11px] leading-5 bg-violet-700 text-white dark:bg-violet-400 dark:text-slate-950"',
  '                  v-slot="{ event }"',
  '                >',
  '                  {{ event.data?.title ?? event.id }}',
  '                </Calendar.MonthTimedEvents>',
  '              </span>',
  '            </Calendar.MonthDays>',
  '',
  '            <Calendar.MonthAllDayEvents',
  '              :gap="BAR_GAP"',
  '              :lanes-top-offset="NUMBER_HEIGHT"',
  '              v-slot="{ event }"',
  '            >',
  '              <span',
  '                :class="[',
  "                  'flex h-full items-center truncate rounded px-1.5 text-[11px] font-medium',",
  "                  'bg-blue-700 text-white dark:bg-blue-300 dark:text-slate-950'",
  '                ]"',
  '              >',
  '                {{ event.data?.title ?? event.id }}',
  '              </span>',
  '            </Calendar.MonthAllDayEvents>',
  '          </Calendar.MonthRows>',
  '        </Calendar.MonthGrid>'
]
