import {
  MONTH_BAR_GAP,
  MONTH_LANE_HEIGHT,
  NUMBER_HEIGHT
} from '@midstem/playground-core'

export const MONTH_HELPERS: readonly string[] = [
  `const LANE_HEIGHT = ${MONTH_LANE_HEIGHT}`,
  `const NUMBER_HEIGHT = ${NUMBER_HEIGHT}`,
  `const BAR_GAP = ${MONTH_BAR_GAP}`,
  ''
]

export const MONTH_BODY: readonly string[] = [
  '        <Calendar.MonthGrid>',
  '          <div',
  '            class="grid border-b border-zinc-200 dark:border-zinc-700"',
  '            style="grid-template-columns: repeat(7, minmax(0, 1fr))"',
  '          >',
  '            <Calendar.MonthWeekdays',
  '              as="span"',
  '              class="border-l border-zinc-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-zinc-500 uppercase first:border-l-0 dark:border-zinc-800 dark:text-zinc-400"',
  '            />',
  '          </div>',
  '',
  '          <Calendar.MonthRows',
  '            class="border-b border-zinc-200 last:border-b-0 dark:border-zinc-700"',
  '            :lane-height="LANE_HEIGHT"',
  '            style="min-height: 116px"',
  '          >',
  '            <Calendar.MonthDays',
  '              class="flex flex-col border-l border-zinc-100 px-1 pb-1 first:border-l-0 dark:border-zinc-800 data-[in-current-period=false]:bg-zinc-50 data-[in-current-period=false]:text-zinc-400 dark:data-[in-current-period=false]:bg-zinc-950"',
  '              v-slot="{ dayLabel, lanes }"',
  '            >',
  '              <span',
  '                class="flex items-center justify-center text-xs font-medium"',
  '                :style="{ height: `${NUMBER_HEIGHT}px` }"',
  '              >',
  '                {{ dayLabel }}',
  '              </span>',
  '',
  '              <span',
  '                class="block"',
  '                :style="{ height: `${lanes * LANE_HEIGHT}px` }"',
  '              />',
  '',
  '              <span class="flex flex-col gap-0.5">',
  '                <Calendar.MonthTimedEvents',
  '                  as="span"',
  '                  class="truncate rounded px-1 text-[11px] leading-5"',
  '                  v-slot="{ event }"',
  '                >',
  '                  {{ event.data?.title }}',
  '                </Calendar.MonthTimedEvents>',
  '              </span>',
  '            </Calendar.MonthDays>',
  '',
  '            <Calendar.MonthAllDayEvents',
  '              :gap="BAR_GAP"',
  '              :lanes-top-offset="NUMBER_HEIGHT"',
  '              v-slot="{ event }"',
  '            >',
  '              <span',
  '                :class="[',
  "                  'flex h-full items-center truncate rounded px-1.5 text-[11px] font-medium',",
  '                  toneOf(event.id)',
  '                ]"',
  '              >',
  '                {{ event.data?.title }}',
  '              </span>',
  '            </Calendar.MonthAllDayEvents>',
  '          </Calendar.MonthRows>',
  '        </Calendar.MonthGrid>'
]
