const BUTTON =
  'rounded-md border border-slate-200 bg-white px-2.5 py-1 text-sm disabled:opacity-40 dark:border-white/15 dark:bg-slate-950'

export const OPENING: readonly string[] = [
  '<template>',
  '  <Calendar.Root',
  '    :range="range"',
  '    :events="EVENTS"',
  '    :locale="LOCALE"',
  '    gutter-width="66px"',
  '    class="flex h-full flex-col p-4 text-slate-900 dark:text-slate-200"',
  '  >',
  '    <template #error="error">',
  '      <p',
  '        role="alert"',
  '        class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950 dark:text-red-300"',
  '      >',
  '        <strong class="font-mono">{{ error.name }}</strong>: {{ error.message }}',
  '      </p>',
  '    </template>',
  '',
  '    <Calendar.Toolbar',
  '      @navigate="range = $event"',
  '      class="flex flex-wrap items-center gap-3 pb-3"',
  '      v-slot="{ navigation, title, goTo }"',
  '    >',
  '      <div class="flex items-center gap-1">',
  '        <button',
  '          type="button"',
  '          aria-label="Previous period"',
  `          class="${BUTTON}"`,
  '          :disabled="!navigation.prev"',
  '          @click="navigation.prev && goTo(navigation.prev)"',
  '        >',
  '          ‹',
  '        </button>',
  '        <button',
  '          type="button"',
  `          class="${BUTTON}"`,
  '          :disabled="!navigation.today"',
  '          @click="navigation.today && goTo(navigation.today())"',
  '        >',
  '          Today',
  '        </button>',
  '        <button',
  '          type="button"',
  '          aria-label="Next period"',
  `          class="${BUTTON}"`,
  '          :disabled="!navigation.next"',
  '          @click="navigation.next && goTo(navigation.next)"',
  '        >',
  '          ›',
  '        </button>',
  '      </div>',
  '',
  '      <h2 class="mr-auto truncate text-lg font-semibold">{{ title }}</h2>',
  '',
  '    </Calendar.Toolbar>',
  '',
  '    <section class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-white/15 dark:bg-slate-950">',
  '      <div class="min-h-0 flex-1 overflow-auto">'
]

export const CLOSING: readonly string[] = [
  '      </div>',
  '    </section>',
  '  </Calendar.Root>',
  '</template>'
]
