const BUTTON =
  'rounded-md border border-zinc-200 bg-white px-2.5 py-1 text-sm disabled:opacity-40 dark:border-zinc-700 dark:bg-zinc-900'

export const OPENING: readonly string[] = [
  '<template>',
  '  <Calendar.Root',
  '    :range="range"',
  '    :events="EVENTS"',
  '    :locale="LOCALE"',
  '    gutter-width="66px"',
  '    class="flex h-full flex-col p-4 text-zinc-900 dark:text-zinc-100"',
  '  >',
  '    <template #error="error">',
  '      <p',
  '        role="alert"',
  '        class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950 dark:text-red-300"',
  '      >',
  '        <strong class="font-mono">{{ error.name }}</strong>: {{ error.message }}',
  '      </p>',
  '    </template>',
  '',
  '    <Calendar.Toolbar',
  '      :views="VIEWS"',
  '      class="flex flex-wrap items-center gap-3 pb-3"',
  '      v-slot="{ navigation, range: shown, title, goTo }"',
  '    >',
  '      <div class="flex items-center gap-1">',
  '        <button',
  '          type="button"',
  '          aria-label="Previous period"',
  `          class="${BUTTON}"`,
  '          :disabled="!navigation.prev"',
  '          @click="navigation.prev && goTo(navigation.prev)"',
  '        >',
  '          ‹',
  '        </button>',
  '        <button',
  '          type="button"',
  `          class="${BUTTON}"`,
  '          :disabled="!navigation.today"',
  '          @click="navigation.today && goTo(navigation.today())"',
  '        >',
  '          Today',
  '        </button>',
  '        <button',
  '          type="button"',
  '          aria-label="Next period"',
  `          class="${BUTTON}"`,
  '          :disabled="!navigation.next"',
  '          @click="navigation.next && goTo(navigation.next)"',
  '        >',
  '          ›',
  '        </button>',
  '      </div>',
  '',
  '      <h2 class="mr-auto truncate text-lg font-semibold">{{ title }}</h2>',
  '',
  '      <div class="flex items-center gap-0.5 rounded-md border border-zinc-200 bg-white p-0.5 dark:border-zinc-700 dark:bg-zinc-900">',
  '        <button',
  '          v-for="kind of VIEWS"',
  '          :key="kind"',
  '          type="button"',
  '          :aria-pressed="kind === shown.view"',
  '          :class="[',
  "            'rounded px-2.5 py-1 text-xs font-medium capitalize',",
  '            kind === shown.view',
  "              ? 'bg-blue-50 text-blue-700 dark:bg-blue-900 dark:text-blue-300'",
  "              : 'text-zinc-500 dark:text-zinc-400'",
  '          ]"',
  '          @click="goTo(navigation.withView(kind))"',
  '        >',
  '          {{ kind }}',
  '        </button>',
  '      </div>',
  '    </Calendar.Toolbar>',
  '',
  '    <section class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900">',
  '      <div class="min-h-0 flex-1 overflow-auto">'
]

export const CLOSING: readonly string[] = [
  '      </div>',
  '    </section>',
  '  </Calendar.Root>',
  '</template>'
]
