import {
  ALL_DAY_LANE_HEIGHT,
  BOX_GAP,
  MIN_BOX_HEIGHT,
  SCROLL_TO_HOUR
} from '@midstem/playground-core'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const ALL_DAY_LANE_HEIGHT = ${ALL_DAY_LANE_HEIGHT}`,
  `const MIN_BOX_HEIGHT = ${MIN_BOX_HEIGHT}`,
  'const COMPACT_BOX_HEIGHT = 36',
  `const BOX_GAP = ${BOX_GAP}`,
  `const SCROLL_TO_HOUR = ${SCROLL_TO_HOUR}`,
  ''
]

export const SLOTTED_BODY: readonly string[] = [
  '        <div class="sticky top-0 z-30 bg-white dark:bg-slate-950">',
  '          <Calendar.Header class="border-b border-slate-200 dark:border-white/15">',
  '            <Calendar.DayHeadings',
  '              class="border-l border-slate-100 py-2 dark:border-white/5"',
  '              v-slot="{ weekdayLabel, dayLabel }"',
  '            >',
  '              <div class="flex flex-col items-center gap-0.5">',
  '                <span class="text-[10px] font-medium tracking-wide text-slate-500 uppercase dark:text-slate-400">',
  '                  {{ weekdayLabel }}',
  '                </span>',
  '                <span class="flex size-7 items-center justify-center text-sm font-semibold">',
  '                  {{ dayLabel }}',
  '                </span>',
  '              </div>',
  '            </Calendar.DayHeadings>',
  '          </Calendar.Header>',
  '',
  '          <Calendar.AllDayRow',
  '            :lane-height="ALL_DAY_LANE_HEIGHT"',
  '            :min-lanes="1"',
  '            class="border-b border-slate-200 pt-0.5 pb-1.5 dark:border-white/15"',
  '          >',
  '            <template #gutterCell>',
  '              <span class="block pt-1 pr-2 text-right text-[10px] text-slate-400 dark:text-slate-400">',
  '                all-day',
  '              </span>',
  '            </template>',
  '            <Calendar.AllDayEvents :gap="5" v-slot="{ event, bar }">',
  '              <span',
  '                :class="[',
  "                  'flex h-full items-center truncate rounded-md px-2 text-[11px] font-medium',",
  "                  'bg-blue-700 text-white dark:bg-blue-300 dark:text-slate-950'",
  '                ]"',
  '              >',
  '                {{ bar.continuesBefore ? "… " : "" }}{{ event.data?.title ?? event.id }}{{ bar.continuesAfter ? " …" : "" }}',
  '              </span>',
  '            </Calendar.AllDayEvents>',
  '          </Calendar.AllDayRow>',
  '        </div>',
  '',
  '        <Calendar.TimeGrid',
  '          :hour-height="HOUR_HEIGHT"',
  '          :scroll-to-hour="SCROLL_TO_HOUR"',
  '        >',
  '          <Calendar.TimeAxis>',
  '            <Calendar.TimeLabels',
  '              class="right-2 text-[10px] tabular-nums text-slate-400 dark:text-slate-400"',
  '              v-slot="{ minuteOfDay, timeLabel }"',
  '            >',
  '              <template v-if="minuteOfDay > 0">{{ timeLabel }}</template>',
  '            </Calendar.TimeLabels>',
  '          </Calendar.TimeAxis>',
  '',
  '          <Calendar.DayColumns class="border-l border-slate-100 dark:border-white/5">',
  '            <Calendar.TimeSlots class="border-t border-slate-100 dark:border-white/5" />',
  '',
  '            <Calendar.NowMarker class="border-t-2 border-orange-600 dark:border-orange-400">',
  '              <span class="absolute -top-[5px] -left-1 size-2 rounded-full bg-orange-600 dark:bg-orange-400" />',
  '            </Calendar.NowMarker>',
  '',
  '            <Calendar.TimedEvents',
  '              class="hover:z-20"',
  '              :min-height="MIN_BOX_HEIGHT"',
  '              :gap="BOX_GAP"',
  '              v-slot="{ event, box }"',
  '            >',
  '              <div',
  '                :class="[',
  "                  'h-full overflow-hidden rounded-md border border-white px-1.5 py-px text-[11px] leading-[1.35] shadow-sm dark:border-slate-900',",
  "                  'bg-violet-700 text-white dark:bg-violet-400 dark:text-slate-950'",
  '                ]"',
  '                :title="`${event.data?.title ?? event.id}\\n${clock(box.start)} – ${clock(box.end)}`"',
  '              >',
  '                <span class="block truncate font-semibold">',
  '                  {{ event.data?.title ?? event.id }}',
  '                </span>',
  '                <span v-if="box.height * HOUR_HEIGHT * 24 >= COMPACT_BOX_HEIGHT" class="block truncate opacity-80">',
  '                  {{ clock(box.start) }} – {{ clock(box.end) }}',
  '                </span>',
  '              </div>',
  '            </Calendar.TimedEvents>',
  '          </Calendar.DayColumns>',
  '        </Calendar.TimeGrid>'
]
