import {
  ALL_DAY_LANE_HEIGHT,
  BOX_GAP,
  MIN_BOX_HEIGHT,
  SCROLL_TO_HOUR
} from '@midstem/playground-core'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const LANE_HEIGHT = ${ALL_DAY_LANE_HEIGHT}`,
  `const MIN_BOX_HEIGHT = ${MIN_BOX_HEIGHT}`,
  `const BOX_GAP = ${BOX_GAP}`,
  `const SCROLL_TO_HOUR = ${SCROLL_TO_HOUR}`,
  ''
]

export const SLOTTED_BODY: readonly string[] = [
  '        <div class="sticky top-0 z-30 bg-white dark:bg-zinc-900">',
  '          <Calendar.Header class="border-b border-zinc-200 dark:border-zinc-700">',
  '            <Calendar.DayHeadings',
  '              class="border-l border-zinc-100 py-2 dark:border-zinc-800"',
  '              v-slot="{ weekdayLabel, dayLabel }"',
  '            >',
  '              <div class="flex flex-col items-center gap-0.5">',
  '                <span class="text-[10px] font-medium tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  '                  {{ weekdayLabel }}',
  '                </span>',
  '                <span class="flex size-7 items-center justify-center text-sm font-semibold">',
  '                  {{ dayLabel }}',
  '                </span>',
  '              </div>',
  '            </Calendar.DayHeadings>',
  '          </Calendar.Header>',
  '',
  '          <Calendar.AllDayRow',
  '            :lane-height="LANE_HEIGHT"',
  '            class="border-b border-zinc-200 pt-0.5 pb-1.5 dark:border-zinc-700"',
  '          >',
  '            <template #gutterCell>',
  '              <span class="block pt-1 pr-2 text-right text-[10px] text-zinc-400 dark:text-zinc-500">',
  '                all-day',
  '              </span>',
  '            </template>',
  '            <Calendar.AllDayEvents v-slot="{ event }">',
  '              <span',
  '                :class="[',
  "                  'flex h-full items-center truncate rounded-md px-2 text-[11px] font-medium',",
  '                  toneOf(event.id)',
  '                ]"',
  '              >',
  '                {{ event.data?.title }}',
  '              </span>',
  '            </Calendar.AllDayEvents>',
  '          </Calendar.AllDayRow>',
  '        </div>',
  '',
  '        <Calendar.TimeGrid',
  '          :hour-height="HOUR_HEIGHT"',
  '          :scroll-to-hour="SCROLL_TO_HOUR"',
  '        >',
  '          <Calendar.TimeAxis>',
  '            <Calendar.TimeLabels',
  '              class="right-2 text-[10px] tabular-nums text-zinc-400 dark:text-zinc-500"',
  '              v-slot="{ minuteOfDay, timeLabel }"',
  '            >',
  '              <template v-if="minuteOfDay > 0">{{ timeLabel }}</template>',
  '            </Calendar.TimeLabels>',
  '          </Calendar.TimeAxis>',
  '',
  '          <Calendar.DayColumns class="border-l border-zinc-100 dark:border-zinc-800">',
  '            <Calendar.TimeSlots class="border-t border-zinc-100 dark:border-zinc-800" />',
  '',
  '            <Calendar.NowMarker class="border-t-2 border-red-600 dark:border-red-400">',
  '              <span class="absolute -top-[5px] -left-1 size-2 rounded-full bg-red-600 dark:bg-red-400" />',
  '            </Calendar.NowMarker>',
  '',
  '            <Calendar.TimedEvents',
  '              class="hover:z-20"',
  '              :min-height="MIN_BOX_HEIGHT"',
  '              :gap="BOX_GAP"',
  '              v-slot="{ event, box }"',
  '            >',
  '              <div',
  '                :class="[',
  "                  'h-full overflow-hidden rounded-md border border-white px-1.5 py-px text-[11px] leading-[1.35] shadow-sm dark:border-zinc-900',",
  '                  toneOf(event.id)',
  '                ]"',
  '                :title="`${event.data?.title}\\n${clock(box.start)} – ${clock(box.end)}`"',
  '              >',
  '                <span class="block truncate font-semibold">',
  '                  {{ event.data?.title }}',
  '                </span>',
  '                <span class="block truncate opacity-80">',
  '                  {{ clock(box.start) }} – {{ clock(box.end) }}',
  '                </span>',
  '              </div>',
  '            </Calendar.TimedEvents>',
  '          </Calendar.DayColumns>',
  '        </Calendar.TimeGrid>'
]
