export const AGENDA_BODY: readonly string[] = [
  '          <ul chronousAgendaList class="divide-y divide-zinc-100 dark:divide-zinc-800">',
  '            <li',
  '              *chronousAgendaDays="',
  '                let day;',
  '                let weekdayLabel = weekdayLabel;',
  '                let dayLabel = dayLabel;',
  '                let bars = bars;',
  '                let boxes = boxes;',
  '                showEmptyDays: true',
  '              "',
  '              class="grid grid-cols-[88px_minmax(0,1fr)] gap-4 px-4 py-3 data-[in-current-period=false]:bg-zinc-50 dark:data-[in-current-period=false]:bg-zinc-800/50"',
  '            >',
  '              <div class="flex items-baseline gap-2">',
  '                <span',
  '                  class="flex size-7 items-center justify-center text-sm font-semibold"',
  '                >',
  '                  {{ dayLabel }}',
  '                </span>',
  '                <span',
  '                  class="text-[11px] tracking-wide text-zinc-500 uppercase dark:text-zinc-400"',
  '                >',
  '                  {{ weekdayLabel }}',
  '                </span>',
  '              </div>',
  '',
  '              <div class="flex flex-col gap-1">',
  '                @if (bars.length === 0 && boxes.length === 0) {',
  '                  <span class="text-[13px] text-zinc-400 dark:text-zinc-500">',
  '                    Nothing on this day',
  '                  </span>',
  '                }',
  '',
  '                <span',
  '                  *chronousAgendaAllDayEvents="bars; let event"',
  '                  class="flex items-center gap-2 text-[13px]"',
  '                >',
  '                  <span',
  '                    class="size-2 shrink-0 rounded-full bg-zinc-400 dark:bg-zinc-500"',
  '                  ></span>',
  '                  <span',
  '                    class="w-24 shrink-0 text-[11px] text-zinc-400 dark:text-zinc-500"',
  '                  >',
  '                    all-day',
  '                  </span>',
  '                  <span class="truncate">{{ event.data.title }}</span>',
  '                </span>',
  '',
  '                <span',
  '                  *chronousAgendaTimedEvents="',
  '                    day;',
  '                    let event;',
  '                    let timeRangeLabel = timeRangeLabel',
  '                  "',
  '                  class="flex items-center gap-2 text-[13px]"',
  '                >',
  '                  <span',
  '                    class="size-2 shrink-0 rounded-full bg-blue-500 dark:bg-blue-400"',
  '                  ></span>',
  '                  <span',
  '                    class="w-24 shrink-0 font-mono text-[11px] tabular-nums text-zinc-500 dark:text-zinc-400"',
  '                  >',
  '                    {{ timeRangeLabel }}',
  '                  </span>',
  '                  <span class="truncate">{{ event.data.title }}</span>',
  '                </span>',
  '              </div>',
  '            </li>',
  '          </ul>'
]
