import {
  MONTH_BAR_GAP,
  MONTH_LANE_HEIGHT,
  MONTH_MAX_LANES,
  NUMBER_HEIGHT
} from '@midstem/playground-core'

export const MONTH_HELPERS: readonly string[] = [
  `const LANE_HEIGHT = ${MONTH_LANE_HEIGHT}`,
  `const MAX_LANES = ${MONTH_MAX_LANES}`,
  `const NUMBER_HEIGHT = ${NUMBER_HEIGHT}`,
  `const BAR_GAP = ${MONTH_BAR_GAP}`,
  ''
]

export const MONTH_BODY: readonly string[] = [
  '          <div chronousMonthGrid>',
  '            <div',
  '              class="grid border-b border-slate-200 dark:border-white/15"',
  '              style="grid-template-columns: repeat(7, minmax(0, 1fr))"',
  '            >',
  '              <span',
  '                *chronousMonthWeekdays="let day; let weekdayLabel = weekdayLabel"',
  '                class="border-l border-slate-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-slate-500 uppercase first:border-l-0 dark:border-white/5 dark:text-slate-400"',
  '              >',
  '                {{ weekdayLabel }}',
  '              </span>',
  '            </div>',
  '',
  '            <div',
  '              *chronousMonthRows="',
  '                let row;',
  '                maxLanes: MAX_LANES;',
  '                laneHeight: LANE_HEIGHT',
  '              "',
  '              class="border-b border-slate-200 last:border-b-0 dark:border-white/15"',
  '              style="min-height: 116px"',
  '            >',
  '              <div',
  '                *chronousMonthDays="',
  '                  row;',
  '                  let day;',
  '                  let dayLabel = dayLabel;',
  '                  let lanes = lanes;',
  '                  let hiddenBars = hiddenBars',
  '                "',
  '                class="flex flex-col border-l border-slate-100 px-1 pb-1 first:border-l-0 dark:border-white/5 data-[in-current-period=false]:bg-slate-50 data-[in-current-period=false]:text-slate-400 dark:data-[in-current-period=false]:bg-slate-800/50"',
  '              >',
  '                <span',
  '                  class="flex items-center justify-center"',
  '                  [style.height.px]="NUMBER_HEIGHT"',
  '                >',
  '                  <span class="text-xs font-medium">{{ dayLabel }}</span>',
  '                </span>',
  '                <span',
  '                  class="block"',
  '                  [style.height.px]="lanes * LANE_HEIGHT"',
  '                ></span>',
  '                @if (hiddenBars.length > 0) {',
  '                  <span',
  '                    class="self-start rounded px-1 font-mono text-[10px] text-slate-500 dark:text-slate-400"',
  '                  >',
  '                    +{{ hiddenBars.length }} more',
  '                  </span>',
  '                }',
  '                <span class="flex flex-col gap-0.5">',
  '                  <span',
  '                    *chronousMonthTimedEvents="day; let event"',
  '                    class="flex items-center gap-1 truncate rounded px-1 text-[11px] leading-5 bg-violet-700 text-white dark:bg-violet-400 dark:text-slate-950 hover:bg-slate-100 dark:hover:bg-slate-800"',
  '                  >',
  '                    <span class="truncate">{{ event.data.title }}</span>',
  '                  </span>',
  '                </span>',
  '              </div>',
  '',
  '              <div',
  '                *chronousMonthAllDayEvents="',
  '                  row;',
  '                  let event;',
  '                  let bar = bar;',
  '                  gap: BAR_GAP;',
  '                  lanesTopOffset: NUMBER_HEIGHT',
  '                "',
  '              >',
  '                <span',
  "                  [class]=\"'flex h-full items-center truncate rounded px-1.5 text-[11px] font-medium ' + 'bg-blue-700 text-white dark:bg-blue-300 dark:text-slate-950'\"",
  '                >',
  '                  {{ event.data.title }}',
  '                </span>',
  '              </div>',
  '            </div>',
  '          </div>'
]
