const BUTTON =
  'rounded-md border border-zinc-200 bg-white px-2.5 py-1 text-sm disabled:opacity-40 dark:border-zinc-700 dark:bg-zinc-900'

export const OPENING: readonly string[] = [
  '@Component({',
  "  selector: 'app-board',",
  '  standalone: true,',
  '  imports: [CALENDAR_DIRECTIVES],',
  '  template: `',
  '    <div',
  '      *chronousCalendar="range(); events: events(); locale: LOCALE; gutterWidth: \'66px\'"',
  '      class="flex h-full flex-col p-4 text-zinc-900 dark:text-zinc-100"',
  '    >',
  '      <div',
  '        *chronousToolbar="let navigation; let title = title"',
  '        class="flex flex-wrap items-center gap-3 pb-3"',
  '      >',
  '        <div class="flex items-center gap-1">',
  '          <button',
  '            type="button"',
  '            aria-label="Previous period"',
  `            class="${BUTTON}"`,
  '            [disabled]="!navigation.prev"',
  '            (click)="range.set(navigation.prev!)"',
  '          >',
  '            ‹',
  '          </button>',
  '          <button',
  '            type="button"',
  `            class="${BUTTON}"`,
  '            [disabled]="!navigation.today"',
  '            (click)="range.set(navigation.today()!)"',
  '          >',
  '            Today',
  '          </button>',
  '          <button',
  '            type="button"',
  '            aria-label="Next period"',
  `            class="${BUTTON}"`,
  '            [disabled]="!navigation.next"',
  '            (click)="range.set(navigation.next!)"',
  '          >',
  '            ›',
  '          </button>',
  '        </div>',
  '',
  '        <h2 class="mr-auto truncate text-lg font-semibold">{{ title }}</h2>',
  '',
  '        <div',
  '          class="flex items-center gap-0.5 rounded-md border border-zinc-200 bg-white p-0.5 dark:border-zinc-700 dark:bg-zinc-900"',
  '        >',
  '          @for (kind of views; track kind) {',
  '            <button',
  '              type="button"',
  '              class="rounded px-2.5 py-1 text-xs font-medium capitalize"',
  '              (click)="range.set(navigation.withView(kind))"',
  '            >',
  '              {{ kind }}',
  '            </button>',
  '          }',
  '        </div>',
  '      </div>',
  '',
  '      <section',
  '        class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900"',
  '      >',
  '        <div class="min-h-0 flex-1 overflow-auto">'
]

export const CLOSING: readonly string[] = [
  '        </div>',
  '      </section>',
  '    </div>',
  '  `',
  '})',
  'export class BoardComponent {',
  '  readonly range = signal<CalendarRange>(INITIAL_RANGE)',
  '  readonly events = signal<EventInput<EventData>[]>(EVENTS)',
  "  readonly views: readonly ViewKind[] = ['day', 'week', 'days', 'month', 'agenda']",
  '}'
]
