import {
  ALL_DAY_LANE_HEIGHT,
  BOX_GAP,
  MIN_BOX_HEIGHT,
  SCROLL_TO_HOUR
} from '@midstem/playground-core'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const LANE_HEIGHT = ${ALL_DAY_LANE_HEIGHT}`,
  `const MIN_BOX_HEIGHT = ${MIN_BOX_HEIGHT}`,
  `const BOX_GAP = ${BOX_GAP}`,
  `const SCROLL_TO_HOUR = ${SCROLL_TO_HOUR}`,
  ''
]

export const SLOTTED_BODY: readonly string[] = [
  '          <div class="sticky top-0 z-30 bg-white dark:bg-zinc-900">',
  '            <div chronousHeader class="border-b border-zinc-200 dark:border-zinc-700">',
  '              <div></div>',
  '              <div',
  '                *chronousDayHeadings="',
  '                  let day;',
  '                  let weekdayLabel = weekdayLabel;',
  '                  let dayLabel = dayLabel',
  '                "',
  '                class="border-l border-zinc-100 py-2 dark:border-zinc-800"',
  '              >',
  '                <div class="flex flex-col items-center gap-0.5">',
  '                  <span class="text-[10px] font-medium tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  '                    {{ weekdayLabel }}',
  '                  </span>',
  '                  <span class="flex size-7 items-center justify-center text-sm font-semibold">',
  '                    {{ dayLabel }}',
  '                  </span>',
  '                </div>',
  '              </div>',
  '            </div>',
  '',
  '            <chronous-all-day-row',
  '              class="border-b border-zinc-200 pt-0.5 pb-1.5 dark:border-zinc-700"',
  '              [laneHeight]="LANE_HEIGHT"',
  '            >',
  '              <span',
  '                chronousGutterCell',
  '                class="block pt-1 pr-2 text-right text-[10px] text-zinc-400 dark:text-zinc-500"',
  '              >',
  '                all-day',
  '              </span>',
  '              <div *chronousAllDayEvents="let event" class="px-px py-px">',
  '                <span',
  '                  [class]="\'flex h-full items-center truncate rounded-md px-2 text-[11px] font-medium \' + toneOf(event.id)"',
  '                >',
  '                  {{ event.data.title }}',
  '                </span>',
  '              </div>',
  '            </chronous-all-day-row>',
  '          </div>',
  '',
  '          <chronous-time-grid [hourHeight]="HOUR_HEIGHT" [scrollToHour]="SCROLL_TO_HOUR">',
  '            <div chronousTimeAxis>',
  '              <div',
  '                *chronousTimeLabels="',
  '                  let slot;',
  '                  let minuteOfDay = minuteOfDay;',
  '                  let timeLabel = timeLabel',
  '                "',
  '                class="right-2 text-[10px] tabular-nums text-zinc-400 dark:text-zinc-500"',
  '              >',
  '                @if (minuteOfDay > 0) {',
  '                  {{ timeLabel }}',
  '                }',
  '              </div>',
  '            </div>',
  '',
  '            <div *chronousDayColumns="let day" class="border-l border-zinc-100 dark:border-zinc-800">',
  '              <span *chronousTimeSlots="day" class="border-t border-zinc-100 dark:border-zinc-800"></span>',
  '',
  '              <div *chronousNowMarker="day" class="border-t-2 border-red-600 dark:border-red-400">',
  '                <span class="absolute -top-[5px] -left-1 size-2 rounded-full bg-red-600 dark:bg-red-400"></span>',
  '              </div>',
  '',
  '              <div',
  '                *chronousTimedEvents="',
  '                  day;',
  '                  let event;',
  '                  let box = box;',
  '                  minHeight: MIN_BOX_HEIGHT;',
  '                  gap: BOX_GAP',
  '                "',
  '                class="hover:z-20"',
  '              >',
  '                <div',
  '                  [class]="\'h-full overflow-hidden rounded-md border border-white px-1.5 py-px text-[11px] leading-[1.35] shadow-sm dark:border-zinc-900 \' + toneOf(event.id)"',
  "                  [attr.title]=\"event.data.title + '\\\\n' + clock(box.start) + ' – ' + clock(box.end)\"",
  '                >',
  '                  <span class="block truncate font-semibold">',
  '                    {{ event.data.title }}',
  '                  </span>',
  '                  @if (box.height * HOUR_HEIGHT * 24 >= 36) {',
  '                    <span class="block truncate opacity-80">',
  '                      {{ clock(box.start) }} – {{ clock(box.end) }}',
  '                    </span>',
  '                  }',
  '                </div>',
  '              </div>',
  '            </div>',
  '          </chronous-time-grid>'
]
