export const AGENDA_HELPERS: readonly string[] = []

export const AGENDA_BODY: readonly string[] = [
  '  return (',
  '    <ul className="h-full divide-y divide-zinc-100 overflow-auto rounded-xl border border-zinc-200 bg-white dark:divide-zinc-800 dark:border-zinc-700 dark:bg-zinc-900">',
  '      {calendar.days.map((day, index) => (',
  '        <li',
  '          key={day.date}',
  '          className={`flex gap-4 px-4 py-3 ${day.inPeriod ? "" : "bg-zinc-50 dark:bg-zinc-950"}`}',
  '        >',
  '          <span className="w-28 shrink-0 text-sm font-medium">',
  '            {formatIso(day.date, {',
  '              locale: LOCALE,',
  "              options: { weekday: 'short', day: 'numeric', month: 'short' }",
  '            })}',
  '          </span>',
  '',
  '          <div className="flex min-w-0 flex-col gap-1">',
  '            {calendar.rows[0].bars',
  '              .filter((bar) => bar.startDay <= index && index < bar.endDay)',
  '              .map((bar) => (',
  '                <span key={bar.event.id} className="flex gap-3 text-sm">',
  '                  <span className="w-28 shrink-0 text-zinc-500">all-day</span>',
  '                  <span className="truncate">{bar.event.data?.title}</span>',
  '                </span>',
  '              ))}',
  '',
  '            {day.boxes.map((box) => (',
  '              <span',
  '                key={`${box.event.id}-${box.startMinute}`}',
  '                className="flex gap-3 text-sm"',
  '              >',
  '                <span className="w-28 shrink-0 tabular-nums text-zinc-500">',
  '                  {formatIso(box.start, {',
  '                    locale: LOCALE,',
  "                    options: { hour: '2-digit', minute: '2-digit' }",
  '                  })}',
  "                  {' – '}",
  '                  {formatIso(box.end, {',
  '                    locale: LOCALE,',
  "                    options: { hour: '2-digit', minute: '2-digit' }",
  '                  })}',
  '                </span>',
  '                <span className="truncate">{box.event.data?.title}</span>',
  '              </span>',
  '            ))}',
  '          </div>',
  '        </li>',
  '      ))}',
  '    </ul>',
  '  )'
]
