export const MONTH_HELPERS: readonly string[] = [
  'const LANE_HEIGHT = 22',
  'const NUMBER_HEIGHT = 24',
  ''
]

export const MONTH_BODY: readonly string[] = [
  '  return (',
  '    <div className="overflow-hidden rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">',
  '      {calendar.rows.map((row, index) => (',
  '        <div',
  '          key={row.start}',
  '          className="relative grid border-b border-zinc-200 last:border-b-0 dark:border-zinc-700"',
  '          style={{',
  '            gridTemplateColumns: `repeat(${row.days}, minmax(0, 1fr))`',
  '          }}',
  '        >',
  '          {calendar.days',
  '            .slice(index * row.days, (index + 1) * row.days)',
  '            .map((day) => (',
  '              <div',
  '                key={day.date}',
  '                className={`min-h-28 border-l border-zinc-100 p-1 first:border-l-0 dark:border-zinc-800 ${day.inPeriod ? "" : "bg-zinc-50 text-zinc-400 dark:bg-zinc-950 dark:text-zinc-500"}`}',
  '              >',
  '                <div',
  '                  className="text-center text-xs font-medium"',
  '                  style={{ height: NUMBER_HEIGHT }}',
  '                >',
  "                  {formatIso(day.date, { locale: LOCALE, options: { day: 'numeric' } })}",
  '                </div>',
  '',
  '                <div style={{ height: row.lanes * LANE_HEIGHT }} />',
  '',
  '                <div className="flex flex-col gap-0.5">',
  '                  {day.boxes.map((box) => (',
  '                    <span',
  '                      key={`${box.event.id}-${box.top}`}',
  '                      className="truncate rounded bg-blue-700 px-1 text-[11px] leading-5 text-white"',
  '                    >',
  '                      {box.event.data?.title}',
  '                    </span>',
  '                  ))}',
  '                </div>',
  '              </div>',
  '            ))}',
  '',
  '          <div',
  '            className="pointer-events-none absolute inset-x-0"',
  '            style={{ top: NUMBER_HEIGHT, height: row.lanes * LANE_HEIGHT }}',
  '          >',
  '            {row.bars.map((bar) => (',
  '              <div',
  '                key={bar.event.id}',
  '                className="absolute truncate rounded bg-violet-700 px-1.5 text-[11px] leading-5 text-white"',
  '                style={{',
  '                  left: `${bar.left * 100}%`,',
  '                  width: `calc(${bar.width * 100}% - 4px)`,',
  '                  top: bar.lane * LANE_HEIGHT',
  '                }}',
  '              >',
  '                {bar.event.data?.title}',
  '              </div>',
  '            ))}',
  '          </div>',
  '        </div>',
  '      ))}',
  '    </div>',
  '  )'
]
