import { HOURS_IN_DAY } from './constants'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const DAY_HEIGHT = HOUR_HEIGHT * ${HOURS_IN_DAY}`,
  'const LANE_HEIGHT = 24',
  ''
]

export const SLOTTED_BODY: readonly string[] = [
  '  const columns = `4rem repeat(${calendar.days.length}, minmax(0, 1fr))`',
  '  const allDay = calendar.rows[0]',
  '',
  '  return (',
  '    <div className="h-full overflow-auto rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900">',
  '      <div',
  '        className="sticky top-0 z-10 grid border-b border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"',
  '        style={{ gridTemplateColumns: columns }}',
  '      >',
  '        <div />',
  '        {calendar.days.map((day) => (',
  '          <div',
  '            key={day.date}',
  '            className="border-l border-zinc-100 py-2 text-center text-sm font-medium dark:border-zinc-800"',
  '          >',
  '            {formatIso(day.date, {',
  '              locale: LOCALE,',
  "              options: { weekday: 'short', day: 'numeric' }",
  '            })}',
  '          </div>',
  '        ))}',
  '      </div>',
  '',
  '      <div',
  '        className="grid border-b border-zinc-200 dark:border-zinc-700"',
  '        style={{ gridTemplateColumns: columns }}',
  '      >',
  '        <div className="py-1 pr-2 text-right text-[10px] text-zinc-400">',
  '          all-day',
  '        </div>',
  '        <div',
  '          className="relative"',
  '          style={{',
  "            gridColumn: '2 / -1',",
  '            height: Math.max(allDay.lanes, 1) * LANE_HEIGHT',
  '          }}',
  '        >',
  '          {allDay.bars.map((bar) => (',
  '            <div',
  '              key={bar.event.id}',
  '              className="absolute truncate rounded bg-violet-700 px-2 text-[11px] leading-5 text-white"',
  '              style={{',
  '                left: `${bar.left * 100}%`,',
  '                width: `calc(${bar.width * 100}% - 4px)`,',
  '                top: bar.lane * LANE_HEIGHT',
  '              }}',
  '            >',
  '              {bar.event.data?.title}',
  '            </div>',
  '          ))}',
  '        </div>',
  '      </div>',
  '',
  '      <div className="grid" style={{ gridTemplateColumns: columns }}>',
  '        <div className="relative" style={{ height: DAY_HEIGHT }}>',
  '          {calendar.days[0].slots.map((slot) => (',
  '            <span',
  '              key={slot.minuteOfDay}',
  '              className="absolute right-2 -translate-y-1/2 text-[10px] text-zinc-400"',
  '              style={{ top: `${(slot.minuteOfDay / 1440) * 100}%` }}',
  '            >',
  '              {formatIso(slot.start, {',
  '                locale: LOCALE,',
  "                options: { hour: '2-digit', minute: '2-digit' }",
  '              })}',
  '            </span>',
  '          ))}',
  '        </div>',
  '',
  '        {calendar.days.map((day) => (',
  '          <div',
  '            key={day.date}',
  '            className="relative border-l border-zinc-100 dark:border-zinc-800"',
  '            style={{ height: DAY_HEIGHT }}',
  '          >',
  '            {day.slots.map((slot) => (',
  '              <span',
  '                key={slot.minuteOfDay}',
  '                className="absolute inset-x-0 border-t border-zinc-100 dark:border-zinc-800"',
  '                style={{ top: `${(slot.minuteOfDay / 1440) * 100}%` }}',
  '              />',
  '            ))}',
  '',
  '            {day.boxes.map((box) => (',
  '              <div',
  '                key={`${box.event.id}-${box.startMinute}`}',
  '                className="absolute overflow-hidden rounded-md bg-blue-700 px-1.5 text-[11px] leading-[1.35] font-medium text-white"',
  '                style={{',
  '                  top: `${box.top * 100}%`,',
  '                  height: `${box.height * 100}%`,',
  '                  left: `${box.left * 100}%`,',
  '                  width: `calc(${box.width * 100}% - 3px)`,',
  '                  minHeight: 22',
  '                }}',
  '              >',
  '                <div className="truncate">{box.event.data?.title}</div>',
  '              </div>',
  '            ))}',
  '          </div>',
  '        ))}',
  '      </div>',
  '    </div>',
  '  )'
]
