export const AGENDA_BODY: readonly string[] = [
  '          <Calendar.AgendaList as="ul" className="divide-y divide-zinc-100 dark:divide-zinc-800">',
  '            <Calendar.AgendaDays',
  '              as="li"',
  '              showEmpty',
  '              className="grid grid-cols-[88px_minmax(0,1fr)] gap-4 px-4 py-3 data-[in-period=false]:bg-zinc-50 dark:data-[in-period=false]:bg-zinc-950"',
  '            >',
  '              {({ weekday, dayNumber, bars, boxes }) => (',
  '                <>',
  '                  <div className="flex items-baseline gap-2">',
  '                    <span className="flex size-7 items-center justify-center text-sm font-semibold">',
  '                      {dayNumber}',
  '                    </span>',
  '                    <span className="text-[11px] tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  '                      {weekday}',
  '                    </span>',
  '                  </div>',
  '',
  '                  <div className="flex flex-col gap-1">',
  '                    {bars.length === 0 && boxes.length === 0 && (',
  '                      <span className="text-[13px] text-zinc-400 dark:text-zinc-500">',
  '                        Nothing on this day',
  '                      </span>',
  '                    )}',
  '',
  '                    <Calendar.AgendaAllDayEvents as="span" className="flex items-center gap-2 text-[13px]">',
  '                      {({ event }) => (',
  '                        <>',
  '                          <span className="w-24 shrink-0 text-[11px] text-zinc-400 dark:text-zinc-500">',
  '                            all-day',
  '                          </span>',
  '                          <span className="truncate">{event.data?.title}</span>',
  '                        </>',
  '                      )}',
  '                    </Calendar.AgendaAllDayEvents>',
  '',
  '                    <Calendar.AgendaTimedEvents as="span" className="flex items-center gap-2 text-[13px]">',
  '                      {({ event, timeRange }) => (',
  '                        <>',
  '                          <span className="w-24 shrink-0 font-mono text-[11px] tabular-nums text-zinc-500 dark:text-zinc-400">',
  '                            {timeRange}',
  '                          </span>',
  '                          <span className="truncate">{event.data?.title}</span>',
  '                        </>',
  '                      )}',
  '                    </Calendar.AgendaTimedEvents>',
  '                  </div>',
  '                </>',
  '              )}',
  '            </Calendar.AgendaDays>',
  '          </Calendar.AgendaList>'
]
