export const AGENDA_HELPERS: readonly string[] = [
  'const clock = (at: IsoDateTime): string =>',
  "  label(at, { hour: '2-digit', minute: '2-digit' })",
  '',
  'const barsOnDay = (calendar: CalendarData<EventData>, index: number) => {',
  '  let taken = 0',
  '',
  '  for (const row of calendar.rows) {',
  '    if (index < taken + row.days) {',
  '      const offset = index - taken',
  '',
  '      return row.bars.filter(',
  '        (bar) => bar.startDay <= offset && offset < bar.endDay',
  '      )',
  '    }',
  '',
  '    taken += row.days',
  '  }',
  '',
  '  return []',
  '}',
  ''
]

export const AGENDA_BODY: readonly string[] = [
  '        <ul className="min-h-0 flex-1 divide-y divide-zinc-100 overflow-auto dark:divide-zinc-800">',
  '          {calendar.days.map((day, index) => (',
  '            <li',
  '              key={day.date}',
  '              className={`grid grid-cols-[88px_minmax(0,1fr)] gap-4 px-4 py-3 ${day.inPeriod ? "" : "bg-zinc-50 dark:bg-zinc-950"}`}',
  '            >',
  '              <div className="flex items-baseline gap-2">',
  '                <span className="flex size-7 items-center justify-center text-sm font-semibold">',
  "                  {label(day.date, { day: 'numeric' })}",
  '                </span>',
  '                <span className="text-[11px] tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  "                  {label(day.date, { weekday: 'short' })}",
  '                </span>',
  '              </div>',
  '',
  '              <div className="flex flex-col gap-1">',
  '                {barsOnDay(calendar, index).map((bar) => (',
  '                  <span',
  '                    key={`${bar.event.id}-${bar.startDay}`}',
  '                    className="flex items-center gap-2 text-[13px]"',
  '                  >',
  '                    <span',
  '                      className={`size-2 shrink-0 rounded-full ${toneOf(bar.event.id)}`}',
  '                    />',
  '                    <span className="w-24 shrink-0 text-[11px] text-zinc-400 dark:text-zinc-500">',
  '                      all-day',
  '                    </span>',
  '                    <span className="truncate">{bar.event.data?.title}</span>',
  '                  </span>',
  '                ))}',
  '',
  '                {day.boxes.map((box) => (',
  '                  <span',
  '                    key={`${box.event.id}-${box.startMinute}`}',
  '                    className="flex items-center gap-2 text-[13px]"',
  '                  >',
  '                    <span',
  '                      className={`size-2 shrink-0 rounded-full ${toneOf(box.event.id)}`}',
  '                    />',
  '                    <span className="w-24 shrink-0 font-mono text-[11px] tabular-nums text-zinc-500 dark:text-zinc-400">',
  '                      {clock(box.start)} – {clock(box.end)}',
  '                    </span>',
  '                    <span className="truncate">{box.event.data?.title}</span>',
  '                  </span>',
  '                ))}',
  '              </div>',
  '            </li>',
  '          ))}',
  '        </ul>'
]
