import type { EventInput, LocaleId, RangeSpec } from '@midstem/chronous'

import { JSON_INDENT } from '../constants'
import type { EventData } from '../types'

import { SPEC_INDENT } from './constants'

const literal = (value: unknown): string =>
  typeof value === 'number' ? String(value) : `'${String(value)}'`

const specLines = (spec: RangeSpec): string =>
  Object.entries(spec)
    .map(([key, value]) => `${SPEC_INDENT}${key}: ${literal(value)}`)
    .join(',\n')

const eventLines = (events: readonly EventInput<EventData>[]): string =>
  JSON.stringify(events, null, JSON_INDENT).replace(
    /"([A-Za-z][\w]*)":/g,
    '$1:'
  )

export const snippetOf = (
  spec: RangeSpec,
  events: readonly EventInput<EventData>[],
  locale: LocaleId,
  hourHeight: number
): string =>
  [
    "import { formatIso } from '@midstem/chronous'",
    "import type { EventInput, IsoDateTime, RangeSpec } from '@midstem/chronous'",
    "import { useCalendar, useCalendarNavigation } from '@midstem/chronous-react'",
    "import { useState } from 'react'",
    '',
    'type EventData = { title: string }',
    '',
    `const LOCALE = '${locale}'`,
    `const HOUR_HEIGHT = ${hourHeight}`,
    'const MINUTES_IN_DAY = 1440',
    'const DAY_HEIGHT = HOUR_HEIGHT * 24',
    '',
    'const INITIAL_SPEC: RangeSpec = {',
    specLines(spec),
    '}',
    '',
    `const EVENTS: EventInput<EventData>[] = ${eventLines(events)}`,
    '',
    'const clock = (at: IsoDateTime): string =>',
    "  formatIso(at, { locale: LOCALE, options: { hour: '2-digit', minute: '2-digit' } })",
    '',
    'const offset = (minuteOfDay: number): string =>',
    '  `${(minuteOfDay / MINUTES_IN_DAY) * 100}%`',
    '',
    'export const Calendar = () => {',
    '  const [spec, setSpec] = useState<RangeSpec>(INITIAL_SPEC)',
    '  const { calendar, error } = useCalendar<EventData>(spec, EVENTS)',
    '  const navigation = useCalendarNavigation(spec)',
    '',
    '  if (error) return <p role="alert">{error.message}</p>',
    '',
    '  return (',
    '    <div>',
    "      <header style={{ display: 'flex', gap: 8 }}>",
    '        <button',
    '          disabled={!navigation.prev}',
    '          onClick={() => navigation.prev && setSpec(navigation.prev)}',
    '        >',
    '          Back',
    '        </button>',
    '        <button',
    '          disabled={!navigation.today}',
    '          onClick={() => navigation.today && setSpec(navigation.today())}',
    '        >',
    '          Today',
    '        </button>',
    '        <button',
    '          disabled={!navigation.next}',
    '          onClick={() => navigation.next && setSpec(navigation.next)}',
    '        >',
    '          Forward',
    '        </button>',
    '      </header>',
    '',
    '      <div',
    '        style={{',
    "          display: 'grid',",
    '          gridTemplateColumns: `64px repeat(${calendar.days.length}, minmax(0, 1fr))`',
    '        }}',
    '      >',
    '        <div />',
    '        {calendar.days.map((day) => (',
    "          <div key={day.date} style={{ textAlign: 'center', fontSize: 12 }}>",
    '            {formatIso(day.date, {',
    '              locale: LOCALE,',
    "              options: { weekday: 'short', day: 'numeric' }",
    '            })}',
    '          </div>',
    '        ))}',
    '',
    "        <div style={{ position: 'relative', height: DAY_HEIGHT }}>",
    '          {calendar.days[0].slots.map((slot) => (',
    '            <span',
    '              key={slot.minuteOfDay}',
    '              style={{',
    "                position: 'absolute',",
    '                right: 8,',
    '                top: offset(slot.minuteOfDay),',
    "                transform: 'translateY(-50%)',",
    '                fontSize: 10',
    '              }}',
    '            >',
    '              {clock(slot.start)}',
    '            </span>',
    '          ))}',
    '        </div>',
    '',
    '        {calendar.days.map((day) => (',
    '          <div',
    '            key={day.date}',
    '            style={{',
    "              position: 'relative',",
    '              height: DAY_HEIGHT,',
    "              borderLeft: '1px solid #e5e7eb'",
    '            }}',
    '          >',
    '            {day.slots.map((slot) => (',
    '              <span',
    '                key={slot.minuteOfDay}',
    '                style={{',
    "                  position: 'absolute',",
    '                  insetInline: 0,',
    '                  top: offset(slot.minuteOfDay),',
    "                  borderTop: '1px solid #f1f3f5'",
    '                }}',
    '              />',
    '            ))}',
    '',
    '            {day.boxes.map((box) => (',
    '              <article',
    '                key={`${box.event.id}-${box.startMinute}`}',
    '                style={{',
    "                  position: 'absolute',",
    '                  top: `${box.top * 100}%`,',
    '                  height: `${box.height * 100}%`,',
    '                  left: `${box.left * 100}%`,',
    '                  width: `calc(${box.width * 100}% - 3px)`,',
    '                  minHeight: 22,',
    "                  overflow: 'hidden',",
    '                  borderRadius: 6,',
    "                  background: '#1a73e8',",
    "                  color: '#fff',",
    '                  fontSize: 11,',
    "                  padding: '1px 6px'",
    '                }}',
    '              >',
    '                <b>{box.event.data?.title}</b> {clock(box.start)}',
    '              </article>',
    '            ))}',
    '          </div>',
    '        ))}',
    '      </div>',
    '    </div>',
    '  )',
    '}'
  ].join('\n')
