import { LANE_HEIGHT } from '../allday/constants'

export const MONTH_HELPERS: readonly string[] = [
  'const NUMBER_HEIGHT = 28',
  'const CELL_MIN_HEIGHT = 116',
  `const LANE_HEIGHT = ${LANE_HEIGHT}`,
  '',
  'const pct = (value: number): string => `${value * 100}%`',
  '',
  'const rowsWithDays = (calendar: CalendarData<EventData>) => {',
  '  let taken = 0',
  '',
  '  return calendar.rows.map((row) => {',
  '    const days = calendar.days.slice(taken, taken + row.days)',
  '',
  '    taken += row.days',
  '',
  '    return { row, days }',
  '  })',
  '}',
  ''
]

export const MONTH_BODY: readonly string[] = [
  '        <div className="min-h-0 flex-1 overflow-auto">',
  '          <div className="flex min-h-full flex-col">',
  '            <div',
  '              className="grid border-b border-zinc-200 dark:border-zinc-700"',
  '              style={{',
  '                gridTemplateColumns: `repeat(${calendar.rows[0].days}, minmax(0, 1fr))`',
  '              }}',
  '            >',
  '              {calendar.days.slice(0, calendar.rows[0].days).map((day) => (',
  '                <span',
  '                  key={day.date}',
  '                  className="border-l border-zinc-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-zinc-500 uppercase first:border-l-0 dark:border-zinc-800 dark:text-zinc-400"',
  '                >',
  "                  {label(day.date, { weekday: 'short' })}",
  '                </span>',
  '              ))}',
  '            </div>',
  '',
  '            {rowsWithDays(calendar).map(({ row, days }) => (',
  '              <div',
  '                key={row.start}',
  '                className="relative flex-1 border-b border-zinc-200 last:border-b-0 dark:border-zinc-700"',
  '                style={{ minHeight: CELL_MIN_HEIGHT }}',
  '              >',
  '                <div',
  '                  className="grid h-full"',
  '                  style={{',
  '                    gridTemplateColumns: `repeat(${days.length}, minmax(0, 1fr))`',
  '                  }}',
  '                >',
  '                  {days.map((day) => (',
  '                    <div',
  '                      key={day.date}',
  '                      className={`flex flex-col border-l border-zinc-100 px-1 pb-1 first:border-l-0 dark:border-zinc-800 ${day.inPeriod ? "" : "bg-zinc-50 text-zinc-400 dark:bg-zinc-950 dark:text-zinc-500"}`}',
  '                    >',
  '                      <span',
  '                        className="flex items-center justify-center"',
  '                        style={{ height: NUMBER_HEIGHT }}',
  '                      >',
  '                        <span className="flex size-6 items-center justify-center text-xs font-medium">',
  "                          {label(day.date, { day: 'numeric' })}",
  '                        </span>',
  '                      </span>',
  '                      <span',
  '                        className="block"',
  '                        style={{ height: row.lanes * LANE_HEIGHT }}',
  '                      />',
  '                      <span className="flex flex-col gap-0.5">',
  '                        {day.boxes.map((box) => (',
  '                          <span',
  '                            key={`${box.event.id}-${box.top}`}',
  '                            className="flex items-center gap-1 truncate rounded px-1 text-[11px] leading-5"',
  '                          >',
  '                            <span',
  '                              className={`size-1.5 shrink-0 rounded-full ${toneOf(box.event.id)}`}',
  '                            />',
  '                            <span className="truncate">',
  '                              {box.event.data?.title}',
  '                            </span>',
  '                          </span>',
  '                        ))}',
  '                      </span>',
  '                    </div>',
  '                  ))}',
  '                </div>',
  '',
  '                <div',
  '                  className="pointer-events-none absolute inset-x-0"',
  '                  style={{',
  '                    top: NUMBER_HEIGHT,',
  '                    height: row.lanes * LANE_HEIGHT',
  '                  }}',
  '                >',
  '                  {row.bars.map((bar) => (',
  '                    <div',
  '                      key={`${bar.event.id}-${bar.startDay}`}',
  '                      className={`absolute truncate rounded px-1.5 text-[11px] leading-[18px] font-medium ${toneOf(bar.event.id)}`}',
  '                      style={{',
  '                        left: `calc(${pct(bar.left)} + 2px)`,',
  '                        width: `calc(${pct(bar.width)} - 4px)`,',
  '                        top: bar.lane * LANE_HEIGHT',
  '                      }}',
  '                    >',
  '                      {bar.event.data?.title}',
  '                    </div>',
  '                  ))}',
  '                </div>',
  '              </div>',
  '            ))}',
  '          </div>',
  '        </div>'
]
