import { BAR_GAP, LANE_HEIGHT, NUMBER_HEIGHT } from '../month/constants'

export const MONTH_HELPERS: readonly string[] = [
  `const LANE_HEIGHT = ${LANE_HEIGHT}`,
  `const NUMBER_HEIGHT = ${NUMBER_HEIGHT}`,
  `const BAR_GAP = ${BAR_GAP}`,
  ''
]

export const MONTH_BODY: readonly string[] = [
  '          <Calendar.MonthGrid>',
  '            <div',
  '              className="grid border-b border-zinc-200 dark:border-zinc-700"',
  '              style={{ gridTemplateColumns: "repeat(7, minmax(0, 1fr))" }}',
  '            >',
  '              <Calendar.MonthWeekdays',
  '                as="span"',
  '                className="border-l border-zinc-100 py-1.5 text-center text-[10px] font-medium tracking-wide text-zinc-500 uppercase first:border-l-0 dark:border-zinc-800 dark:text-zinc-400"',
  '              />',
  '            </div>',
  '',
  '            <Calendar.MonthRows',
  '              className="border-b border-zinc-200 last:border-b-0 dark:border-zinc-700"',
  '              style={{ minHeight: 116 }}',
  '            >',
  '              <Calendar.MonthDays className="flex flex-col border-l border-zinc-100 px-1 pb-1 first:border-l-0 dark:border-zinc-800 data-[in-period=false]:bg-zinc-50 data-[in-period=false]:text-zinc-400 dark:data-[in-period=false]:bg-zinc-950">',
  '                {({ dayNumber, lanes }) => (',
  '                  <>',
  '                    <span',
  '                      className="flex items-center justify-center text-xs font-medium"',
  '                      style={{ height: NUMBER_HEIGHT }}',
  '                    >',
  '                      {dayNumber}',
  '                    </span>',
  '',
  '                    <span',
  '                      className="block"',
  '                      style={{ height: lanes * LANE_HEIGHT }}',
  '                    />',
  '',
  '                    <span className="flex flex-col gap-0.5">',
  '                      <Calendar.MonthEntries',
  '                        as="span"',
  '                        className="truncate rounded px-1 text-[11px] leading-5"',
  '                      >',
  '                        {({ event }) => event.data?.title}',
  '                      </Calendar.MonthEntries>',
  '                    </span>',
  '                  </>',
  '                )}',
  '              </Calendar.MonthDays>',
  '',
  '              <Calendar.MonthBars',
  '                laneHeight={LANE_HEIGHT}',
  '                gap={BAR_GAP}',
  '                topOffset={NUMBER_HEIGHT}',
  '              >',
  '                {({ event }) => (',
  '                  <span',
  '                    className={`flex h-full items-center truncate rounded px-1.5 text-[11px] font-medium ${toneOf(event.id)}`}',
  '                  >',
  '                    {event.data?.title}',
  '                  </span>',
  '                )}',
  '              </Calendar.MonthBars>',
  '            </Calendar.MonthRows>',
  '          </Calendar.MonthGrid>'
]
