const SLOTTED_HOOKS: readonly string[] = [
  '  const [at, setAt] = useState(() => new Date())',
  '  const scroller = useRef<HTMLDivElement>(null)',
  '',
  '  useEffect(() => {',
  '    const timer = window.setInterval(() => setAt(new Date()), TICK_MS)',
  '',
  '    return () => window.clearInterval(timer)',
  '  }, [])',
  '',
  '  useEffect(() => {',
  '    scroller.current?.scrollTo({ top: HOUR_HEIGHT * SCROLL_TO_HOUR - 8 })',
  '  }, [])',
  '',
  '  const now = nowIn(spec.timeZone, at)',
  ''
]

export const openingOf = (slotted: boolean): readonly string[] => [
  'export const Calendar = () => {',
  '  const [spec, setSpec] = useState<RangeSpec>(INITIAL_SPEC)',
  '  const { calendar, error } = useCalendar<EventData>(spec, EVENTS)',
  '  const navigation = useCalendarNavigation(spec)',
  '',
  ...(slotted ? SLOTTED_HOOKS : []),
  '  if (error)',
  '    return (',
  '      <p',
  '        role="alert"',
  '        className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950 dark:text-red-300"',
  '      >',
  '        <strong className="font-mono">{error.name}</strong>: {error.message}',
  '      </p>',
  '    )',
  '',
  '  return (',
  '    <div className="flex h-full flex-col p-4 text-zinc-900 dark:text-zinc-100">',
  '      <header className="flex flex-wrap items-center gap-3 pb-3">',
  '        <div className="flex items-center gap-1">',
  '          <button',
  '            type="button"',
  '            aria-label="Previous period"',
  '            className="rounded-md border border-zinc-200 bg-white px-2.5 py-1 text-sm disabled:opacity-40 dark:border-zinc-700 dark:bg-zinc-900"',
  '            disabled={!navigation.prev}',
  '            onClick={() => navigation.prev && setSpec(navigation.prev)}',
  '          >',
  '            ‹',
  '          </button>',
  '          <button',
  '            type="button"',
  '            className="rounded-md border border-zinc-200 bg-white px-2.5 py-1 text-sm disabled:opacity-40 dark:border-zinc-700 dark:bg-zinc-900"',
  '            disabled={!navigation.today}',
  '            onClick={() => navigation.today && setSpec(navigation.today())}',
  '          >',
  '            Today',
  '          </button>',
  '          <button',
  '            type="button"',
  '            aria-label="Next period"',
  '            className="rounded-md border border-zinc-200 bg-white px-2.5 py-1 text-sm disabled:opacity-40 dark:border-zinc-700 dark:bg-zinc-900"',
  '            disabled={!navigation.next}',
  '            onClick={() => navigation.next && setSpec(navigation.next)}',
  '          >',
  '            ›',
  '          </button>',
  '        </div>',
  '',
  '        <h2 className="mr-auto truncate text-lg font-semibold">',
  '          {titleOf(calendar)}',
  '        </h2>',
  '',
  '        <div className="flex items-center gap-0.5 rounded-md border border-zinc-200 bg-white p-0.5 dark:border-zinc-700 dark:bg-zinc-900">',
  '          {VIEWS.map((kind) => (',
  '            <button',
  '              key={kind}',
  '              type="button"',
  '              aria-pressed={kind === spec.view}',
  '              className={`rounded px-2.5 py-1 text-xs font-medium capitalize ${kind === spec.view ? "bg-blue-50 text-blue-700 dark:bg-blue-900 dark:text-blue-300" : "text-zinc-500 dark:text-zinc-400"}`}',
  '              onClick={() => setSpec(navigation.withView(kind))}',
  '            >',
  '              {kind}',
  '            </button>',
  '          ))}',
  '        </div>',
  '      </header>',
  '',
  '      <section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900">'
]

export const CLOSING: readonly string[] = [
  '      </section>',
  '    </div>',
  '  )',
  '}'
]
