import { LANE_HEIGHT } from '../allday/constants'
import {
  COMPACT_BOX_HEIGHT,
  GUTTER_WIDTH,
  MIN_BOX_HEIGHT
} from '../grid/constants'

import { HOURS_IN_DAY } from './constants'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const DAY_HEIGHT = HOUR_HEIGHT * ${HOURS_IN_DAY}`,
  `const GUTTER_WIDTH = ${GUTTER_WIDTH}`,
  `const MIN_BOX_HEIGHT = ${MIN_BOX_HEIGHT}`,
  `const COMPACT_BOX_HEIGHT = ${COMPACT_BOX_HEIGHT}`,
  `const LANE_HEIGHT = ${LANE_HEIGHT}`,
  'const MINUTES_IN_DAY = 1440',
  'const MINUTES_IN_HOUR = 60',
  'const HOURS_IN_DAY = 24',
  'const SCROLL_TO_HOUR = 7',
  'const TICK_MS = 30000',
  '',
  'const pct = (value: number): string => `${value * 100}%`',
  '',
  'const clock = (at: IsoDateTime): string =>',
  "  label(at, { hour: '2-digit', minute: '2-digit' })",
  '',
  "const pad = (value: number): string => String(value).padStart(2, '0')",
  '',
  'const wallTime = (date: IsoDate, minuteOfDay: number): IsoDateTime =>',
  '  `${date}T${pad(Math.floor(minuteOfDay / MINUTES_IN_HOUR))}:${pad(minuteOfDay % MINUTES_IN_HOUR)}:00`',
  '',
  'const templateOf = (columns: number): string =>',
  '  `${GUTTER_WIDTH}px repeat(${columns}, minmax(0, 1fr))`',
  '',
  'const nowIn = (timeZone: string, at: Date) => {',
  '  try {',
  "    const date = new Intl.DateTimeFormat('en-CA', {",
  '      timeZone,',
  "      year: 'numeric',",
  "      month: '2-digit',",
  "      day: '2-digit'",
  '    }).format(at)',
  '',
  "    const reading = new Intl.DateTimeFormat('en-GB', {",
  '      timeZone,',
  "      hour: '2-digit',",
  "      minute: '2-digit',",
  '      hour12: false',
  '    }).format(at)',
  '',
  "    const [hour, minute] = reading.split(':').map(Number)",
  '',
  '    return {',
  '      date,',
  '      minuteOfDay: (hour % HOURS_IN_DAY) * MINUTES_IN_HOUR + minute',
  '    }',
  '  } catch {',
  '    return null',
  '  }',
  '}',
  ''
]

export const SLOTTED_BODY: readonly string[] = [
  '        <div ref={scroller} className="min-h-0 flex-1 overflow-auto">',
  '          <div className="sticky top-0 z-30 bg-white dark:bg-zinc-900">',
  '            <div',
  '              className="grid border-b border-zinc-200 dark:border-zinc-700"',
  '              style={{ gridTemplateColumns: templateOf(calendar.days.length) }}',
  '            >',
  '              <div />',
  '              {calendar.days.map((day) => (',
  '                <div',
  '                  key={day.date}',
  '                  className="flex flex-col items-center gap-0.5 border-l border-zinc-100 py-2 dark:border-zinc-800"',
  '                >',
  '                  <span className="text-[10px] font-medium tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  "                    {label(day.date, { weekday: 'short' })}",
  '                  </span>',
  '                  <span className="flex size-7 items-center justify-center text-sm font-semibold">',
  "                    {label(day.date, { day: 'numeric' })}",
  '                  </span>',
  '                </div>',
  '              ))}',
  '            </div>',
  '',
  '            {calendar.rows[0] && (',
  '              <div',
  '                className="grid border-b border-zinc-200 dark:border-zinc-700"',
  '                style={{',
  '                  gridTemplateColumns: templateOf(calendar.days.length)',
  '                }}',
  '              >',
  '                <div className="pt-1 pr-2 text-right text-[10px] text-zinc-400 dark:text-zinc-500">',
  '                  all-day',
  '                </div>',
  '                <div',
  '                  className="relative"',
  '                  style={{',
  "                    gridColumn: '2 / -1',",
  '                    height:',
  '                      Math.max(calendar.rows[0].lanes, 1) * LANE_HEIGHT + 6',
  '                  }}',
  '                >',
  '                  {calendar.rows[0].bars.map((bar) => (',
  '                    <div',
  '                      key={`${bar.event.id}-${bar.startDay}`}',
  '                      className={`absolute truncate rounded-md px-2 text-[11px] leading-5 font-medium ${toneOf(bar.event.id)}`}',
  '                      style={{',
  '                        left: `calc(${pct(bar.left)} + 2px)`,',
  '                        width: `calc(${pct(bar.width)} - 5px)`,',
  '                        top: bar.lane * LANE_HEIGHT + 2',
  '                      }}',
  '                    >',
  '                      {bar.event.data?.title}',
  '                    </div>',
  '                  ))}',
  '                </div>',
  '              </div>',
  '            )}',
  '          </div>',
  '',
  '          <div',
  '            className="grid"',
  '            style={{ gridTemplateColumns: templateOf(calendar.days.length) }}',
  '          >',
  '            <div className="relative" style={{ height: DAY_HEIGHT }}>',
  '              {calendar.days[0].slots.map((slot) => (',
  '                <span',
  '                  key={slot.minuteOfDay}',
  '                  className="absolute right-2 -translate-y-1/2 text-[10px] tabular-nums text-zinc-400 dark:text-zinc-500"',
  '                  style={{ top: pct(slot.minuteOfDay / MINUTES_IN_DAY) }}',
  '                >',
  '                  {slot.minuteOfDay > 0 &&',
  '                    clock(wallTime(calendar.days[0].date, slot.minuteOfDay))}',
  '                </span>',
  '              ))}',
  '            </div>',
  '',
  '            {calendar.days.map((day) => (',
  '              <div',
  '                key={day.date}',
  '                className="relative border-l border-zinc-100 dark:border-zinc-800"',
  '                style={{ height: DAY_HEIGHT }}',
  '              >',
  '                {day.slots.map((slot) => (',
  '                  <span',
  '                    key={slot.minuteOfDay}',
  '                    className="absolute inset-x-0 border-t border-zinc-100 dark:border-zinc-800"',
  '                    style={{ top: pct(slot.minuteOfDay / MINUTES_IN_DAY) }}',
  '                  />',
  '                ))}',
  '',
  '                {now?.date === day.date && (',
  '                  <span',
  '                    className="absolute inset-x-0 z-10 border-t-2 border-red-600 dark:border-red-400"',
  '                    style={{ top: pct(now.minuteOfDay / MINUTES_IN_DAY) }}',
  '                  >',
  '                    <span className="absolute -top-[5px] -left-1 size-2 rounded-full bg-red-600 dark:bg-red-400" />',
  '                  </span>',
  '                )}',
  '',
  '                {day.boxes.map((box) => (',
  '                  <div',
  '                    key={`${box.event.id}-${box.startMinute}`}',
  '                    className={`absolute overflow-hidden rounded-md border border-white px-1.5 py-px text-[11px] leading-[1.35] shadow-sm hover:z-20 dark:border-zinc-900 ${toneOf(box.event.id)}`}',
  '                    style={{',
  '                      top: pct(box.top),',
  '                      height: pct(box.height),',
  '                      left: pct(box.left),',
  '                      width: `calc(${pct(box.width)} - 3px)`,',
  '                      minHeight: MIN_BOX_HEIGHT',
  '                    }}',
  '                    title={`${box.event.data?.title}\\n${clock(box.start)} – ${clock(box.end)}`}',
  '                  >',
  '                    <span className="block truncate font-semibold">',
  '                      {box.event.data?.title}',
  '                    </span>',
  '                    {box.height * DAY_HEIGHT >= COMPACT_BOX_HEIGHT && (',
  '                      <span className="block truncate opacity-80">',
  '                        {clock(box.start)} – {clock(box.end)}',
  '                      </span>',
  '                    )}',
  '                  </div>',
  '                ))}',
  '              </div>',
  '            ))}',
  '          </div>',
  '        </div>'
]
