import { LANE_HEIGHT } from '../allday/constants'
import { BOX_GAP, MIN_BOX_HEIGHT, SCROLL_TO_HOUR } from '../grid/constants'

export const slottedHelpers = (hourHeight: number): readonly string[] => [
  `const HOUR_HEIGHT = ${hourHeight}`,
  `const LANE_HEIGHT = ${LANE_HEIGHT}`,
  `const MIN_BOX_HEIGHT = ${MIN_BOX_HEIGHT}`,
  `const BOX_GAP = ${BOX_GAP}`,
  `const SCROLL_TO_HOUR = ${SCROLL_TO_HOUR}`,
  ''
]

export const SLOTTED_BODY: readonly string[] = [
  '          <div className="sticky top-0 z-30 bg-white dark:bg-zinc-900">',
  '            <Calendar.Header className="border-b border-zinc-200 dark:border-zinc-700">',
  '              <Calendar.DayHeadings className="border-l border-zinc-100 py-2 dark:border-zinc-800">',
  '                {({ weekdayLabel, dayLabel }) => (',
  '                  <div className="flex flex-col items-center gap-0.5">',
  '                    <span className="text-[10px] font-medium tracking-wide text-zinc-500 uppercase dark:text-zinc-400">',
  '                      {weekdayLabel}',
  '                    </span>',
  '                    <span className="flex size-7 items-center justify-center text-sm font-semibold">',
  '                      {dayLabel}',
  '                    </span>',
  '                  </div>',
  '                )}',
  '              </Calendar.DayHeadings>',
  '            </Calendar.Header>',
  '',
  '            <Calendar.AllDayRow',
  '              laneHeight={LANE_HEIGHT}',
  '              className="border-b border-zinc-200 pt-0.5 pb-1.5 dark:border-zinc-700"',
  '              gutterCell={',
  '                <span className="block pt-1 pr-2 text-right text-[10px] text-zinc-400 dark:text-zinc-500">',
  '                  all-day',
  '                </span>',
  '              }',
  '            >',
  '              <Calendar.AllDayEvents>',
  '                {({ event }) => (',
  '                  <span',
  '                    className={`flex h-full items-center truncate rounded-md px-2 text-[11px] font-medium ${toneOf(event.id)}`}',
  '                  >',
  '                    {event.data?.title}',
  '                  </span>',
  '                )}',
  '              </Calendar.AllDayEvents>',
  '            </Calendar.AllDayRow>',
  '          </div>',
  '',
  '          <Calendar.TimeGrid',
  '            hourHeight={HOUR_HEIGHT}',
  '            scrollToHour={SCROLL_TO_HOUR}',
  '          >',
  '            <Calendar.TimeAxis>',
  '              <Calendar.TimeLabels className="right-2 text-[10px] tabular-nums text-zinc-400 dark:text-zinc-500">',
  '                {({ minuteOfDay, timeLabel }) => (minuteOfDay > 0 ? timeLabel : null)}',
  '              </Calendar.TimeLabels>',
  '            </Calendar.TimeAxis>',
  '',
  '            <Calendar.DayColumns className="border-l border-zinc-100 dark:border-zinc-800">',
  '              <Calendar.TimeSlots className="border-t border-zinc-100 dark:border-zinc-800" />',
  '',
  '              <Calendar.NowMarker className="border-t-2 border-red-600 dark:border-red-400">',
  '                <span className="absolute -top-[5px] -left-1 size-2 rounded-full bg-red-600 dark:bg-red-400" />',
  '              </Calendar.NowMarker>',
  '',
  '              <Calendar.TimedEvents',
  '                className="hover:z-20"',
  '                minHeight={MIN_BOX_HEIGHT}',
  '                gap={BOX_GAP}',
  '              >',
  '                {({ event, box }) => (',
  '                  <div',
  '                    className={`h-full overflow-hidden rounded-md border border-white px-1.5 py-px text-[11px] leading-[1.35] shadow-sm dark:border-zinc-900 ${toneOf(event.id)}`}',
  '                    title={`${event.data?.title}\\n${clock(box.start)} – ${clock(box.end)}`}',
  '                  >',
  '                    <span className="block truncate font-semibold">',
  '                      {event.data?.title}',
  '                    </span>',
  '                    <span className="block truncate opacity-80">',
  '                      {clock(box.start)} – {clock(box.end)}',
  '                    </span>',
  '                  </div>',
  '                )}',
  '              </Calendar.TimedEvents>',
  '            </Calendar.DayColumns>',
  '          </Calendar.TimeGrid>'
]
